services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: friends_split
      MYSQL_USER: friends
      MYSQL_PASSWORD: friends_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_pass"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql+pymysql://friends:friends_pass@db:3306/friends_split?charset=utf8mb4
      SECRET_KEY: change_me_very_long_random
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080
      CORS_ORIGINS: "*"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://hesab.tabaro.ir/api/v1}
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-https://hesab.tabaro.ir/api/v1}
    depends_on:
      - backend

volumes:
  db_data:
